# Generated by Django 5.0.4 on 2024-05-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('owner', models.BigIntegerField()),
                ('picture', models.ImageField(upload_to='images')),
                ('published_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
